// Mutation constants

const LOGIN_USER = 'LOGIN_USER'
const LOGOUT_USER = 'LOGOUT_USER'
const UPDATE_USER = 'UPDATE_USER'
const REFRESH_DATA = 'REFRESH_DATA'
const SET_RECENT_WORKOUTS = 'SET_RECENT_WORKOUTS'

export {
  LOGIN_USER,
  LOGOUT_USER,
  UPDATE_USER,
  REFRESH_DATA,
  SET_RECENT_WORKOUTS
}
