# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 05:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20160920_0341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='set',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='set',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='exercise',
            name='date_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='date_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='date_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
