# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workout_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='set',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
