# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_auto_20161101_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='display_name',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.CharField(blank=True, help_text='A human easy to read/share name for exercise', max_length=15, null=True, unique=True),
        ),
    ]
