# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_auto_20161104_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilograms'), ('LB', 'Pounds')], default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='weight',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
