# Generated by Django 2.0.7 on 2018-08-31 21:53

import os
import json

from django.db import migrations
from django.conf import settings


def load_exercises(apps, schema_editor):
    WORKOUT_SEEDS_PATH = os.path.join(settings.BASE_DIR, "workouts", "seeds")

    ExerciseType = apps.get_model("workouts", "ExerciseType")
    MuscleGroup = apps.get_model("workouts", "MuscleGroup")

    with open(os.path.join(WORKOUT_SEEDS_PATH, "exercises.json"), "r") as read_file:
        data = json.load(read_file)

        for item in data:
            muscle_name = item["name"]
            exercises = item["exercises"]

            muscle_group, _ = MuscleGroup.objects.get_or_create(name=muscle_name)

            for name in exercises:
                ExerciseType.objects.get_or_create(name=name, muscle_group=muscle_group)


class Migration(migrations.Migration):

    dependencies = [("workouts", "0001_squashed_0008_auto_20180831_1959")]

    operations = [migrations.RunPython(load_exercises)]
