# Generated by Django 2.0.4 on 2018-07-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20180509_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='status',
            field=models.CharField(
                choices=[('IN_PROGRESS', 'In Progress'),
                         ('CANCELLED', 'Cancelled'), ('COMPLETE', 'Complete')],
                default='IN_PROGRESS',
                max_length=32),
        ),
    ]
