# Generated by Django 2.0.4 on 2018-07-11 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0002_auto_20180509_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='status',
            field=models.CharField(
                choices=[('IN_PROGRESS', 'In Progress'),
                         ('CANCELLED', 'Cancelled'), ('COMPLETE', 'Complete')],
                default='IN_PROGRESS',
                max_length=32),
        ),
    ]
