# Generated by Django 2.0.7 on 2018-09-01 01:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workouts", "0002_auto_20180831_2153"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisetype",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name="exercisetype", unique_together={("user", "name")}
        ),
    ]
