# Generated by Django 2.0.4 on 2018-07-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20180711_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='type',
            new_name='exercise_type',
        ),
    ]
