# Generated by Django 2.1.2 on 2018-10-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20180901_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='bodyweight',
            field=models.BooleanField(default=False),
        ),
    ]
