# Generated by Django 2.0.4 on 2018-07-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20180711_2121'),
        ('workouts', '0004_auto_20180711_1639'),
    ]

    operations = []
