# Generated by Django 2.0.7 on 2018-08-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_auto_20180714_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('CANCELLED', 'Cancelled'), ('COMPLETE', 'Complete')], default='PENDING', max_length=32),
        ),
    ]
