# Generated by Django 2.2.4 on 2019-08-10 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workouts", "0006_auto_20190804_1939"),
    ]

    operations = [
        migrations.RemoveField(model_name="exercise", name="date_ended"),
        migrations.RemoveField(model_name="exercise", name="date_started"),
        migrations.RemoveField(model_name="set", name="date_ended"),
        migrations.RemoveField(model_name="set", name="date_started"),
        migrations.RemoveField(model_name="workoutevent", name="message"),
        migrations.AddField(
            model_name="musclegroup",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="date_ended",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp workout ended", null=True
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="date_started",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp workout started", null=True
            ),
        ),
    ]
