# Generated by Django 2.2.4 on 2019-08-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("workouts", "0007_auto_20190810_1356")]

    operations = [
        migrations.RenameField(
            model_name="workout", old_name="date_ended", new_name="ended_at"
        ),
        migrations.RenameField(
            model_name="workout", old_name="date_started", new_name="started_at"
        ),
        migrations.AddField(
            model_name="exercise",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="ended_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp Exercise ended", null=True
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="started_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp Exercise started", null=True
            ),
        ),
        migrations.AddField(
            model_name="set",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="ended_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp Set ended", null=True
            ),
        ),
        migrations.AddField(
            model_name="set",
            name="started_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp Set started", null=True
            ),
        ),
        migrations.AlterField(
            model_name="set",
            name="unit",
            field=models.CharField(
                choices=[("KG", "Kilograms"), ("LB", "Pounds")],
                default="LB",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="set",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
