# Generated by Django 2.2.4 on 2019-08-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_auto_20190810_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisetype',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='musclegroup',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='workoutevent',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
