# Generated by Django 2.0.4 on 2018-05-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(default='NOT_SET', max_length=32),
        ),
    ]
