# Generated by Django 2.2.4 on 2019-08-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0004_auto_20190804_1939")]

    operations = [
        migrations.RemoveField(model_name="profile", name="date_created"),
        migrations.RemoveField(model_name="profile", name="is_active"),
    ]
