# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_modified',
        ),
    ]
